version: "2"
services:
  mesh-service:
    container_name: mesh-service
    build:
      context: .
      dockerfile: docker_conf/Dockerfile
    image: nginx:latest
    ports:
      - 8180:80
    volumes:
      - .:/var/www/service
    links:
      - mysql:mysql
  mysql:
    image: mysql:5.7
    ports:
      - 13307:3306
    restart: always
    environment:
      MYSQL_DATABASE: mesh-service
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root